const {chromium}=require('C:/Users/grey/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{const p=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:8774';await p.goto(base+'/?date=2026-03-01#map-component');await p.locator('.basin-shape').first().waitFor();assert.equal(await p.locator('#map-date').inputValue(),'2026-03-01');assert.match(await p.locator('#date-reading').textContent(),/March 1, 2026/);assert.match(await p.locator('#map-metric-title').textContent(),/Percent/);
for(const width of [320,390,768,1440]){await p.setViewportSize({width,height:900});await p.evaluate(()=>document.fonts.ready);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no overflow '+width);}
for(const id of await p.locator('.basin-shape').evaluateAll(els=>els.map(e=>e.dataset.region))){await p.locator('.basin-shape[data-region="'+id+'"]').focus();await p.keyboard.press('Enter');assert.equal(await p.locator('#region').inputValue(),id);assert.equal(await p.locator(':focus').getAttribute('data-region'),id);assert.equal(await p.locator('.basin-row.is-selected').getAttribute('data-region'),id);assert.match(await p.locator('#date-reading').textContent(),/March 1, 2026/);}
await p.selectOption('#region','co-gunnison');assert.equal(await p.locator('.basin-shape[aria-pressed="true"]').getAttribute('data-region'),'co-gunnison');await p.selectOption('#season','2025');assert.equal(await p.locator('#map-date').inputValue(),'2025-03-01');await p.locator('#day').focus();await p.keyboard.press('ArrowRight');assert.equal(await p.locator('#map-date').inputValue(),'2025-03-02');await p.locator('#map-latest').click();assert.equal(await p.locator('#map-date').inputValue(),'2026-09-21');assert.match(await p.locator('#map-metric-title').textContent(),/inches/);await p.selectOption('#map-metric','median');assert.equal(await p.locator('#basin-map-list').getByText('Median near zero',{exact:true}).count(),8);await p.selectOption('#map-metric','auto');
await p.locator('#region').focus();const focus=await p.locator('#region').evaluate(e=>({outline:getComputedStyle(e).outlineStyle,weight:getComputedStyle(e).fontWeight}));assert.equal(focus.outline,'none');assert.equal(focus.weight,'700');
const download=p.waitForEvent('download');await p.locator('#map-export').click();await(await download).saveAs('../../outputs/ColoradoSnowpack-newsletter-map-latest.png');
await p.route('**/assets/colorado-basins.json',r=>r.fulfill({status:503,body:'Unavailable'}));await p.reload();await p.locator('#chart svg').waitFor();assert.match(await p.locator('#basin-map-canvas').textContent(),/could not load/);assert.deepEqual(errors,[]);console.log('PASS: four widths; eight keyboard-selected basins; focus retention; menu, chart year and date synchronization; summer fallback; explicit median mode; newsletter PNG; subtle focus/bold selection; failed map preserves chart.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
