const {chromium}=require('C:/Users/grey/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('node:fs');const assert=require('node:assert/strict');const path=require('node:path');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});try{
const page=await browser.newPage();const errors=[],checks=[];page.on('pageerror',e=>errors.push(String(e)));const base='http://127.0.0.1:8765';const out=path.resolve('../../outputs');
await page.goto(base);await page.locator('#dashboard').waitFor({state:'visible'});assert(await page.locator('.landscape img').evaluate(img=>img.complete&&img.naturalWidth>0),'landscape loads');assert((await page.request.get(base+'/assets/manrope-latin.woff2')).ok(),'local font loads');const dataPath=await page.locator('body').getAttribute('data-snapshot');const snap=await(await page.request.get(base+'/'+dataPath)).json();
for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});await page.reload();await page.locator('#dashboard').waitFor({state:'visible'});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(width<400){const b=await page.locator('#swe').boundingBox();assert(b.y+b.height<760,'current reading visible in a short phone viewport');}checks.push('Layout '+width+'px; no overflow');}
await page.setViewportSize({width:1440,height:1000});await page.goto(base);await page.locator('#dashboard').waitFor({state:'visible'});await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(out,'ColoradoSnowpack-polished-desktop.png'),fullPage:true});
await page.locator('#region').selectOption('co-colorado-headwaters');assert.match(await page.locator('#chart-title').textContent(),/Headwaters/);await page.locator('#season').selectOption('2025');assert.match(await page.locator('#chart-title').textContent(),/2025/);await page.locator('#day').focus();const before=await page.locator('#day').inputValue();await page.keyboard.press('ArrowLeft');assert.notEqual(await page.locator('#day').inputValue(),before);assert(await page.locator('#day').getAttribute('aria-valuetext'));checks.push('Region, year and keyboard date controls');
await page.locator('summary').click();assert.equal(await page.locator('tbody tr').count(),366);checks.push('Accessible 366-row table');
for(const ext of ['csv','json']){const url=await page.locator('.download-links a').filter({hasText:ext.toUpperCase()}).getAttribute('href');assert.equal((await page.request.get(base+'/'+url)).status(),200);}checks.push('Versioned CSV/JSON downloads');
await page.goto(base);await page.keyboard.press('Tab');assert.equal(await page.locator(':focus').textContent(),'Skip to content');await page.keyboard.press('Enter');assert.equal(await page.locator(':focus').getAttribute('id'),'main');checks.push('Keyboard skip link');
const touch=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const phone=await touch.newPage();await phone.goto(base);await phone.locator('#dashboard').waitFor({state:'visible'});await phone.evaluate(()=>document.fonts.ready);await phone.screenshot({path:path.join(out,'ColoradoSnowpack-polished-mobile.png'),fullPage:true});await phone.evaluate(()=>document.fonts.ready);await phone.screenshot({path:path.join(out,'ColoradoSnowpack-polished-mobile-first-screen.png')});await phone.locator('summary').tap();assert(await phone.locator('.table-wrap').isVisible());await phone.locator('#day').tap();checks.push('Phone touch date control and table');await touch.close();
for(const [name,date,value,median,pattern]of [['winter','2026-02-01',8,10,/80%/],['zero','2026-02-01',0,10,/0%/],['off-season','2026-09-21',.04,0,/median for this date is zero/],['missing','2026-09-21',null,0,/unavailable/]]){const f=structuredClone(snap);f.observation_date=date;const r=f.regions[0],i=r.dates.indexOf(date.slice(5));r.years['2026'][i]=value;r.median[i]=median;await page.route('**/snapshot.json',r=>r.fulfill({json:f}));await page.goto(base);await page.locator('#dashboard').waitFor({state:'visible'});assert.match(await page.locator('#condition-title').textContent(),pattern);await page.unroute('**/snapshot.json');checks.push(name+' state');}
const stale=structuredClone(snap);stale.observation_date='2024-09-21';stale.status='accepted';await page.route('**/snapshot.json',r=>r.fulfill({json:stale}));await page.goto(base);await page.locator('#dashboard').waitFor({state:'visible'});assert.match(await page.locator('#snapshot-status').textContent(),/overdue/);await page.unroute('**/snapshot.json');checks.push('Stale warning');
await page.route('**/snapshot.json',r=>r.fulfill({status:503,body:'Unavailable'}));await page.goto(base);await page.locator('#load-error').waitFor({state:'visible'});assert.equal(await page.locator('#dashboard').isVisible(),false);await page.unroute('**/snapshot.json');await page.locator('#retry').click();await page.locator('#dashboard').waitFor({state:'visible'});checks.push('Failure and retry');assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'ColoradoSnowpack-visual-QA.json'),JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({checks,errors}));
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
